feat:Extend default routes with html route only if html loaded
RadicalImaging/OHIFExtensionsAndModes pull request #23
Opened 2022-12-09 22:27 UTC by wayfarer3130

This change allows viewing html reports alongside annotation/markup SR objects

2022-12-09 22:27 UTC, wayfarer3130 commented
@md-prog - can you review please?

2022-12-12 21:27 UTC, md-prog requested changes
Other than increasing versions of the packages and its dependencies, looks good.

- config-mode : version upgrade
- findings-mode : config-mode dependency and version upgrade
- dicom-html : config-mode dependency version upgrade

2022-12-12 21:28 UTC, md-prog approved these changes

2022-12-12 22:16 UTC, merged

2022-12-12 22:16 UTC, wayfarer3130 commented
Going to update the package versions on main as part of a release build